// GENERATED by scripts/build-locale.mjs from i18n/locales.json and i18n/<locale>/_scripts.json; edit those, then run npm run locales (docs/DEPLOYMENT.md#languages).
import { translator } from '../assets/translate.js'

export const SOURCE_LOCALE = "en"
export const LOCALES = {
  "en": {
    "name": "English",
    "englishName": "English",
    "intl": "en",
    "lang": "en"
  },
  "ru": {
    "name": "Русский",
    "englishName": "Russian",
    "intl": "ru-RU",
    "lang": "ru"
  },
  "es": {
    "name": "Español",
    "englishName": "Spanish",
    "intl": "es",
    "lang": "es"
  },
  "pt-br": {
    "name": "Português (Brasil)",
    "englishName": "Brazilian Portuguese",
    "intl": "pt-BR",
    "lang": "pt-BR"
  }
}
export const CATALOGS = {
  "ru": {
    "Request not sent": "Заявка не отправлена",
    "Your request was not sent": "Ваша заявка не отправлена",
    "You can also write to {email}.": "Можно также написать на {email}.",
    "Back to the form": "Вернуться к форме",
    "The form is not accepting requests right now. Please write to {email} instead.": "Сейчас форма не принимает заявки. Пожалуйста, напишите на {email}.",
    "Too many requests from your network in the last minute. Please wait a minute and try again.": "За последнюю минуту из вашей сети пришло слишком много заявок. Подождите минуту и попробуйте снова.",
    "The request is too long.": "Заявка слишком длинная.",
    "The request could not be read.": "Не удалось прочитать заявку.",
    "That was faster than a person can fill the form. Please check your answers and send it again.": "Форма заполнена быстрее, чем это может сделать человек. Проверьте ответы и отправьте ещё раз.",
    "The form has expired. Reload the page and send it again — your answers are kept in the browser.": "Срок действия формы истёк. Перезагрузите страницу и отправьте заявку снова — ответы сохранены в браузере.",
    "Some answers need another look.": "Некоторые ответы нужно проверить.",
    "This form was already sent once. Reload the page to send another request — your answers are kept in the browser.": "Эта форма уже была отправлена. Чтобы отправить новую заявку, перезагрузите страницу — ответы сохранены в браузере.",
    "We could not save your request. Nothing was sent. Please try again in a minute or write to {email}.": "Не удалось сохранить заявку, ничего не отправлено. Попробуйте через минуту или напишите на {email}.",
    "This request was already sent with different answers. Reload the page to start a new one.": "Эта заявка уже была отправлена с другими ответами. Перезагрузите страницу, чтобы начать новую.",
    "We received your request — PassionCode.ai": "Мы получили вашу заявку — PassionCode.ai",
    "Hello,": "Здравствуйте!",
    "Thank you for your request. It reached PassionCode.ai.": "Спасибо за заявку. Она дошла до PassionCode.ai.",
    "What happens next:": "Что будет дальше:",
    "1. We read what you sent and reply within two business days, usually with a few questions about the processes you named.": "1. Мы прочитаем то, что вы прислали, и ответим в течение двух рабочих дней — обычно с несколькими вопросами о названных вами процессах.",
    "2. If it fits, we suggest a short call to map one process and agree how to measure it.": "2. Если задача нам подходит, предложим короткий созвон, чтобы разобрать один процесс и договориться, как его измерять.",
    "3. You get a written proposal: what we would set up, where it runs, and the license it needs.": "3. Вы получите письменное предложение: что мы настроим, где это будет работать и какая лицензия для этого нужна.",
    "Everything PassionCode.ai builds is open source under the GNU AGPL-3.0, so you can also start on your own today: {start}": "Всё, что делает PassionCode.ai, — открытый код под GNU AGPL-3.0, поэтому начать можно и самостоятельно уже сегодня: {start}",
    "To add anything, reply to this email.": "Чтобы что-то добавить, просто ответьте на это письмо.",
    "Reference: {id}. We keep your request only to answer it: {privacy}": "Номер заявки: {id}. Мы храним заявку только для того, чтобы ответить на неё: {privacy}",
    "required": "обязательное поле",
    "at least {n} characters": {
      "one": "не меньше {n} символа",
      "few": "не меньше {n} символов",
      "many": "не меньше {n} символов",
      "other": "не меньше {n} символа"
    },
    "at most {n} characters": {
      "one": "не больше {n} символа",
      "few": "не больше {n} символов",
      "many": "не больше {n} символов",
      "other": "не больше {n} символа"
    },
    "a number from 0 to {max}": "число от 0 до {max}",
    "choose one of the listed answers": "выберите один из предложенных ответов",
    "unknown answer": "неизвестный ответ",
    "choose at least one": "выберите хотя бы один вариант",
    "choose at least {n}": "выберите не меньше {n}",
    "a web address": "адрес сайта",
    "a work email address": "рабочий адрес почты",
    "agree to the privacy notice to send the request": "чтобы отправить заявку, согласитесь с уведомлением о конфиденциальности"
  },
  "es": {
    "Request not sent": "Solicitud no enviada",
    "Your request was not sent": "Tu solicitud no se ha enviado",
    "You can also write to {email}.": "También puedes escribir a {email}.",
    "Back to the form": "Volver al formulario",
    "The form is not accepting requests right now. Please write to {email} instead.": "Ahora mismo el formulario no acepta solicitudes. Escribe a {email}, por favor.",
    "Too many requests from your network in the last minute. Please wait a minute and try again.": "Se han recibido demasiadas solicitudes desde tu red en el último minuto. Espera un minuto e inténtalo de nuevo.",
    "The request is too long.": "La solicitud es demasiado larga.",
    "The request could not be read.": "No se ha podido leer la solicitud.",
    "That was faster than a person can fill the form. Please check your answers and send it again.": "El formulario se ha completado más rápido de lo que podría hacerlo una persona. Revisa tus respuestas y envíalo de nuevo.",
    "The form has expired. Reload the page and send it again — your answers are kept in the browser.": "El formulario ha caducado. Recarga la página y envíalo de nuevo: tus respuestas se conservan en el navegador.",
    "Some answers need another look.": "Algunas respuestas necesitan una revisión.",
    "This form was already sent once. Reload the page to send another request — your answers are kept in the browser.": "Este formulario ya se envió una vez. Recarga la página para enviar otra solicitud: tus respuestas se conservan en el navegador.",
    "We could not save your request. Nothing was sent. Please try again in a minute or write to {email}.": "No hemos podido guardar tu solicitud. No se ha enviado nada. Inténtalo de nuevo en un minuto o escribe a {email}.",
    "This request was already sent with different answers. Reload the page to start a new one.": "Esta solicitud ya se envió con otras respuestas. Recarga la página para empezar una nueva.",
    "We received your request — PassionCode.ai": "Hemos recibido tu solicitud — PassionCode.ai",
    "Hello,": "Hola:",
    "Thank you for your request. It reached PassionCode.ai.": "Gracias por tu solicitud. Ha llegado a PassionCode.ai.",
    "What happens next:": "Qué ocurre ahora:",
    "1. We read what you sent and reply within two business days, usually with a few questions about the processes you named.": "1. Leemos lo que nos enviaste y respondemos en un plazo de dos días hábiles, normalmente con algunas preguntas sobre los procesos que mencionaste.",
    "2. If it fits, we suggest a short call to map one process and agree how to measure it.": "2. Si encaja, te proponemos una llamada breve para describir un proceso y acordar cómo medirlo.",
    "3. You get a written proposal: what we would set up, where it runs, and the license it needs.": "3. Recibes una propuesta por escrito: qué configuraríamos, dónde funcionaría y qué licencia necesita.",
    "Everything PassionCode.ai builds is open source under the GNU AGPL-3.0, so you can also start on your own today: {start}": "Todo lo que construye PassionCode.ai es código abierto bajo la GNU AGPL-3.0, así que también puedes empezar por tu cuenta hoy mismo: {start}",
    "To add anything, reply to this email.": "Si quieres añadir algo, responde a este correo.",
    "Reference: {id}. We keep your request only to answer it: {privacy}": "Referencia: {id}. Conservamos tu solicitud solo para responderla: {privacy}",
    "required": "obligatorio",
    "at least {n} characters": {
      "one": "al menos {n} carácter",
      "many": "al menos {n} caracteres",
      "other": "al menos {n} caracteres"
    },
    "at most {n} characters": {
      "one": "como máximo {n} carácter",
      "many": "como máximo {n} caracteres",
      "other": "como máximo {n} caracteres"
    },
    "a number from 0 to {max}": "un número de 0 a {max}",
    "choose one of the listed answers": "elige una de las respuestas de la lista",
    "unknown answer": "respuesta desconocida",
    "choose at least one": "elige al menos una opción",
    "choose at least {n}": "elige al menos {n}",
    "a web address": "una dirección web",
    "a work email address": "un correo de trabajo",
    "agree to the privacy notice to send the request": "acepta el aviso de privacidad para enviar la solicitud"
  },
  "pt-br": {
    "Request not sent": "Solicitação não enviada",
    "Your request was not sent": "Sua solicitação não foi enviada",
    "You can also write to {email}.": "Você também pode escrever para {email}.",
    "Back to the form": "Voltar ao formulário",
    "The form is not accepting requests right now. Please write to {email} instead.": "O formulário não está aceitando solicitações no momento. Escreva para {email}.",
    "Too many requests from your network in the last minute. Please wait a minute and try again.": "Houve solicitações demais da sua rede no último minuto. Aguarde um minuto e tente novamente.",
    "The request is too long.": "A solicitação é longa demais.",
    "The request could not be read.": "Não foi possível ler a solicitação.",
    "That was faster than a person can fill the form. Please check your answers and send it again.": "O formulário foi preenchido mais rápido do que uma pessoa consegue. Confira as respostas e envie de novo.",
    "The form has expired. Reload the page and send it again — your answers are kept in the browser.": "O formulário expirou. Recarregue a página e envie novamente. Suas respostas ficam guardadas no navegador.",
    "Some answers need another look.": "Algumas respostas precisam ser revisadas.",
    "This form was already sent once. Reload the page to send another request — your answers are kept in the browser.": "Este formulário já foi enviado. Para enviar outra solicitação, recarregue a página. Suas respostas ficam guardadas no navegador.",
    "We could not save your request. Nothing was sent. Please try again in a minute or write to {email}.": "Não conseguimos salvar a sua solicitação e nada foi enviado. Tente novamente em um minuto ou escreva para {email}.",
    "This request was already sent with different answers. Reload the page to start a new one.": "Esta solicitação já foi enviada com respostas diferentes. Recarregue a página para começar uma nova.",
    "We received your request — PassionCode.ai": "Recebemos a sua solicitação — PassionCode.ai",
    "Hello,": "Olá,",
    "Thank you for your request. It reached PassionCode.ai.": "Obrigado pela sua solicitação. Ela chegou à PassionCode.ai.",
    "What happens next:": "O que acontece agora:",
    "1. We read what you sent and reply within two business days, usually with a few questions about the processes you named.": "1. Lemos o que você enviou e respondemos em até dois dias úteis, geralmente com algumas perguntas sobre os processos que você citou.",
    "2. If it fits, we suggest a short call to map one process and agree how to measure it.": "2. Se fizer sentido, sugerimos uma conversa rápida para mapear um processo e combinar como medi-lo.",
    "3. You get a written proposal: what we would set up, where it runs, and the license it needs.": "3. Você recebe uma proposta por escrito: o que configuraríamos, onde rodaria e qual licença seria necessária.",
    "Everything PassionCode.ai builds is open source under the GNU AGPL-3.0, so you can also start on your own today: {start}": "Tudo o que a PassionCode.ai desenvolve é código aberto sob a GNU AGPL-3.0, então você também pode começar por conta própria hoje mesmo: {start}",
    "To add anything, reply to this email.": "Para acrescentar algo, basta responder a este e-mail.",
    "Reference: {id}. We keep your request only to answer it: {privacy}": "Referência: {id}. Guardamos a sua solicitação apenas para respondê-la: {privacy}",
    "required": "obrigatório",
    "at least {n} characters": {
      "one": "pelo menos {n} caractere",
      "many": "pelo menos {n} de caracteres",
      "other": "pelo menos {n} caracteres"
    },
    "at most {n} characters": {
      "one": "no máximo {n} caractere",
      "many": "no máximo {n} de caracteres",
      "other": "no máximo {n} caracteres"
    },
    "a number from 0 to {max}": "um número de 0 a {max}",
    "choose one of the listed answers": "escolha uma das respostas listadas",
    "unknown answer": "resposta desconhecida",
    "choose at least one": "escolha pelo menos uma opção",
    "choose at least {n}": "escolha pelo menos {n}",
    "a web address": "um endereço da web",
    "a work email address": "um e-mail de trabalho",
    "agree to the privacy notice to send the request": "concorde com o aviso de privacidade para enviar a solicitação"
  }
}
export const { resolveLocale, t, tn } = translator({ source: SOURCE_LOCALE, locales: LOCALES, catalogs: CATALOGS })
